name: EKS Cluster

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  eks_cluster:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [create, destroy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform init
        run: terraform init
        working-directory: eks

      - name: Terraform apply or destroy
        run: |
          if [ "${{ matrix.environment }}" == "create" ]; then
            terraform apply --auto-approve
          elif [ "${{ matrix.environment }}" == "destroy" ]; then
            terraform destroy --auto-approve
          fi
        working-directory: eks
